
name: Python testi ar unittest  

on: [push]  

jobs:
  testi:
    runs-on: ubuntu-latest  
    
    steps:
      - name: 1. Ielādē kodu
        uses: actions/checkout@v3
        
      
      - name: 2. Iestata Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      
      - name: 3. Palaiž testus
        run: python -m unittest discover
        